version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:11.15
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn setup
      - run: yarn build
workflows:
  universal_kickback_all:
    jobs:
      - build
