name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      uses: actions/setup-node@v1
      with:
        node-version: 11.x
    - name: yarn install and build
      run: |
        yarn install
        yarn setup
        yarn build
      env:
        CI: true
